apiVersion: skaffold/v2beta21
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infa/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ducnguyen96/mini-microservice-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: ducnguyen96/mini-microservice-commentservice
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: ducnguyen96/mini-microservice-eventbus
      context: events
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: ducnguyen96/mini-microservice-moderationservice
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: ducnguyen96/mini-microservice-postservice
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: ducnguyen96/mini-microservice-queryservice
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
